import type { Metadata } from "next";
import { Roboto } from "next/font/google";

// CSS Global
import "./globals.css";

// Components
import { Navbar } from "@/components/Navbar/page";
import { Footer } from "@/components/Footer/page";

// Providers do Context
import { UserProvider } from "@/context/UserContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // escolha os pesos que vai usar
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Orkkut",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body className={`${roboto.variable} antialiased`}>
        <UserProvider>
          <Navbar />
          <div className="site-content">{children}</div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}

export default RootLayout;
