import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// CSS Global
import "./globals.css";

// Components
import { Navbar } from "@/components/Navbar/page";
import { Footer } from "@/components/Footer/page";

// Providers do Context
import { UserProvider } from "@/context/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Orkkut",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <Navbar />
          <div className="site-content">{children}</div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
